AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '

  Application for triggering functions when order proposal is created.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-order-proposal-utilities
    Description: Utility functions triggered by order proposal
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/3dd9cfbd058e9688d7d654aa16c6ca08
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/OrderProposalUtilities
    SemanticVersion: 1.1.0
    SourceCodeUrl: https://github.com/thetis-apps/OrderProposalUtilities
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Type: String
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Globals:
  Function:
    Runtime: nodejs16.x
    MemorySize: 512
    Timeout: 3
Resources:
  OrderProposalHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a relevant document is created within Thetis
        IMS
      Handler: src/app.orderProposalHandler
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - documentCreated
              detail:
                documentType:
                - ORDER_PROPOSAL
                contextId:
                - Ref: ContextId
      Timeout: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/798e2e18fd68cb7284266c5d276ee693
    Metadata:
      SamResourceId: OrderProposalHandler
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Metadata:
      SamResourceId: DeadLetterQueue
