AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: '

  Application for automating purchasing procedures at Yarnliving

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-yarnliving-purchasing
    Description: Application for automating purchasing procedures at Yarnliving.
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/4612b8d5aa75b9b9936c9b7b9e6c7e82
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/2e7ffbd561475c21c7f0783863a328bd
    Labels:
    - thetis-ims
    HomePageUrl: https://github.com/thetis-apps/YarnlivingPurchasing
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/thetis-apps/YarnlivingPurchasing
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Type: String
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter
      queue.
    Type: String
    MinLength: 4
Globals:
  Function:
    Runtime: nodejs16.x
    MemorySize: 512
    Timeout: 3
Resources:
  OrderProposalHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a relevant document is created within Thetis
        IMS
      Handler: src/app.orderProposalHandler
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          ContextId:
            Ref: ContextId
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - documentCreated
              detail:
                documentType:
                - ORDER_PROPOSAL
                contextId:
                - Ref: ContextId
      Timeout: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3/b7f7b725fbeb495ca4340e599b502ab6
    Metadata:
      SamResourceId: OrderProposalHandler
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: {}
    Metadata:
      SamResourceId: DeadLetterQueue
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when any message is moved to the dead letter queue.
      AlarmActions:
      - Ref: IncidentTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Period: 60
      Namespace: AWS/SQS
      Threshold: '0'
      Unit: Count
      Dimensions:
      - Name: QueueName
        Value:
          Fn::GetAtt:
          - DeadLetterQueue
          - QueueName
      TreatMissingData: notBreaching
      Statistic: Maximum
    Metadata:
      SamResourceId: Alarm
  IncidentTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: DevOpsEmail
        Protocol: email
      DisplayName: Incidents to be handled by Thetis Devops.
    Metadata:
      SamResourceId: IncidentTopic
